-- Skema database Jasa Kolam Renang Bogor.
-- Jalankan lewat phpMyAdmin (Import atau tab SQL) pada database yang
-- sudah dibuat di hPanel. Aman dijalankan berkali-kali (IF NOT EXISTS).

CREATE TABLE IF NOT EXISTS business (
  id TINYINT UNSIGNED NOT NULL DEFAULT 1 PRIMARY KEY,
  name VARCHAR(191) NOT NULL DEFAULT '',
  legalName VARCHAR(191) NOT NULL DEFAULT '',
  tagline VARCHAR(255) NOT NULL DEFAULT '',
  description TEXT,
  phoneDisplay VARCHAR(50) NOT NULL DEFAULT '',
  phoneHref VARCHAR(50) NOT NULL DEFAULT '',
  whatsapp VARCHAR(50) NOT NULL DEFAULT '',
  whatsappMessage TEXT,
  email VARCHAR(191) NOT NULL DEFAULT '',
  addressLine VARCHAR(255) NOT NULL DEFAULT '',
  city VARCHAR(100) NOT NULL DEFAULT '',
  region VARCHAR(100) NOT NULL DEFAULT '',
  postalCode VARCHAR(20) NOT NULL DEFAULT '',
  country VARCHAR(10) NOT NULL DEFAULT 'ID',
  hoursWeekday VARCHAR(100) NOT NULL DEFAULT '',
  hoursWeekend VARCHAR(100) NOT NULL DEFAULT '',
  mapsQuery VARCHAR(255) NOT NULL DEFAULT '',
  mapsUrl TEXT,
  priceRange VARCHAR(10) NOT NULL DEFAULT '',
  yearsExperience INT NOT NULL DEFAULT 0,
  projectsDone INT NOT NULL DEFAULT 0,
  domain VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS areas (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  link VARCHAR(255) NOT NULL DEFAULT '',
  description TEXT,
  lat DECIMAL(10,6) DEFAULT NULL,
  lng DECIMAL(10,6) DEFAULT NULL,
  priority TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS faq (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  question VARCHAR(500) NOT NULL,
  answer TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS portfolio (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(191) NOT NULL,
  area VARCHAR(100) NOT NULL DEFAULT '',
  description TEXT,
  image VARCHAR(500) DEFAULT NULL,
  color1 VARCHAR(20) DEFAULT NULL,
  color2 VARCHAR(20) DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
